### ISSUE TITLE
Don't forget to format your code

### ISSUE THREAD

**Issue by Johan-Mi** [Tomas-Ka/Fred#1]
Preferably before every commit to keep your code as readable as possible. Python has several formatters available, such as AutoPEP8 or Black.

**Comment by Tomas-Ka** [comment]
This was mostly a way to send my code from a pc to another with some source control xD but I went and ran it through AutoPEP8, and that certainly made a difference for readability, thanks! (fixed in 6d3d4fbbd810f5a21c4f58d40a8c57077bfc9979)
